#!/usr/bin/env bash
# This script displays "Best School" 10 times and says "Hi" during the 9th

x=1
while [ "$x" -le 10 ]
do
    echo "Best School"
    if [ "$x" -eq 9 ]; then
	echo "Hi"
    fi
    (( x++ ))
done
