#!/usr/bin/env bash
# Prints "Best School" 10x, "bad luck" the 4th, "good luck" the 8th

x=1
while [ "$x" -le 10 ]
do
    if [ "$x" -eq 4 ]; then
	echo "bad luck"
    elif [ "$x" -eq 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( x++ ))
done
