#!/usr/bin/env bash
# Prints 1 to 20; "bad luck from China" the 4th,
# "bad luck from Japan" the 9th, and "bad luck from Italy" the 17th

x=1
while [ "$x" -le 20 ]
do
    echo "$x"
    case $x in
	4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
    esac
    (( x++ ))
done
